services:
  postgres:
    image: postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATABASE_USER:-conexa}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-conexa}
      POSTGRES_DB: ${DATABASE_NAME:-conexa_movies}
    ports:
      - '${DATABASE_PORT:-5432}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DATABASE_USER:-conexa}']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
